import { desc, eq } from "drizzle-orm";
import { ArrowDownToLine, Clock3, History, Landmark, Wallet } from "lucide-react";
import Image from "next/image";
import { db } from "@/db";
import { walletTransactions, withdrawals } from "@/db/schema";
import { requireUser } from "@/lib/auth/guards";
import { WithdrawalForm } from "@/components/dashboard/WithdrawalForm";
import { Empty, PageHeader, cardClass, sectionTitleClass } from "@/components/dashboard/ui";
import { formatVnd, minWithdrawal } from "@/lib/config";
import { txTypeLabel, withdrawalStatusClass, withdrawalStatusLabel } from "@/lib/labels";

export const metadata = { title: "Ví của bạn — Win-Win Back" };
export const dynamic = "force-dynamic";
function Stat({ icon: Icon, label, value, tone }: { icon: typeof Wallet; label: string; value: string; tone: string }) { return <div className={cardClass}><div className="flex items-center gap-3"><span className={`flex h-11 w-11 items-center justify-center rounded-full ${tone}`}><Icon className="h-5 w-5" /></span><div><p className="text-xs text-[#6681a7]">{label}</p><p className="mt-1 text-xl font-black tracking-tight text-[#0d315d]">{value}</p></div></div></div>; }

export default async function WalletPage() {
  const user = await requireUser();
  const [transactions, withdrawalsRows] = await Promise.all([db.select().from(walletTransactions).where(eq(walletTransactions.userId, user.id)).orderBy(desc(walletTransactions.createdAt)).limit(100), db.select().from(withdrawals).where(eq(withdrawals.userId, user.id)).orderBy(desc(withdrawals.requestedAt)).limit(50)]);
  const waitingAmount = withdrawalsRows.filter((item) => item.status === "pending").reduce((sum, item) => sum + item.amount, 0);
  const withdrawnAmount = withdrawalsRows.filter((item) => item.status === "paid").reduce((sum, item) => sum + item.amount, 0);
  return <main className="mx-auto max-w-[1440px] px-4 py-7 sm:px-7 lg:px-6 lg:py-8"><PageHeader icon={Wallet} title="Ví hoàn tiền" hint="Theo dõi số dư, lịch sử giao dịch và rút tiền về tài khoản của bạn." />
    <section className="relative mb-5 min-h-52 overflow-hidden rounded-xl bg-[#ecfae4] p-5 sm:min-h-48 sm:p-6"><Image src="/images/dashboard-wallet-promo-v2.png" alt="" fill sizes="(max-width: 640px) 100vw, 80rem" className="object-contain object-right sm:object-cover sm:object-center" /><div className="relative z-10 max-w-[10rem] sm:max-w-[22rem]"><p className="text-lg font-black text-[#164b37] sm:hidden">Ví hoàn tiền an toàn</p><p className="hidden text-lg font-black text-[#164b37] sm:block">Tiền hoàn được giữ an toàn trong ví</p><p className="mt-2 text-sm leading-6 text-[#356b54] sm:hidden">Tiền về ví sau khi đơn hoàn tất.</p><p className="mt-2 hidden text-sm leading-6 text-[#356b54] sm:block">Khi đơn hàng hoàn tất, số dư sẽ được cập nhật để bạn rút về tài khoản ngân hàng.</p></div></section>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Stat icon={Wallet} label="Số dư khả dụng" value={formatVnd(user.balance)} tone="bg-[#ecfae4] text-[#4aab1b]" /><Stat icon={Clock3} label="Tiền chờ duyệt" value={formatVnd(waitingAmount)} tone="bg-[#fff5dc] text-[#ed9b07]" /><Stat icon={ArrowDownToLine} label="Tổng đã rút" value={formatVnd(withdrawnAmount)} tone="bg-[#eaf2ff] text-[#287be5]" /><Stat icon={Landmark} label="Rút tối thiểu" value={formatVnd(minWithdrawal)} tone="bg-[#f7e9ff] text-[#aa34de]" /></div>
    <section className="mt-5 grid gap-5 xl:grid-cols-[minmax(0,1fr)_23rem]"><div className={`${cardClass} overflow-hidden p-0`}><div className="flex items-center gap-2 border-b border-[#e6edf6] px-4 py-4 sm:px-5"><History className="h-4 w-4 text-[#287be5]" /><h2 className={sectionTitleClass}>Lịch sử giao dịch ví</h2></div>{transactions.length === 0 ? <div className="p-5"><Empty text="Chưa có giao dịch ví nào." /></div> : <div className="overflow-x-auto"><table className="min-w-[720px] w-full text-left text-sm"><thead className="bg-[#f8fbff] text-xs text-[#6681a7]"><tr><th className="px-5 py-3 font-semibold">Thời gian</th><th className="px-4 py-3 font-semibold">Nội dung</th><th className="px-4 py-3 font-semibold">Số tiền</th><th className="px-4 py-3 font-semibold">Số dư sau</th></tr></thead><tbody className="divide-y divide-[#e8eef6]">{transactions.map((item) => <tr key={item.id}><td className="px-5 py-4 text-[#6681a7]">{item.createdAt.toLocaleString("vi-VN")}</td><td className="px-4 py-4"><b className="block text-[#244a7c]">{txTypeLabel[item.type]}</b><span className="text-xs text-[#6681a7]">{item.note}</span></td><td className={`px-4 py-4 font-bold ${item.amount >= 0 ? "text-[#19813e]" : "text-red-500"}`}>{item.amount >= 0 ? "+" : ""}{formatVnd(item.amount)}</td><td className="px-4 py-4 text-[#315a90]">{formatVnd(item.balanceAfter)}</td></tr>)}</tbody></table></div>}</div><aside className="space-y-4"><div className={cardClass}><div className="mb-4 flex items-center gap-2"><span className="flex h-9 w-9 items-center justify-center rounded-lg bg-[#ecfae4] text-[#4aab1b]"><ArrowDownToLine className="h-4 w-4" /></span><h2 className={sectionTitleClass}>Rút tiền</h2></div><WithdrawalForm balance={user.balance} minWithdrawal={minWithdrawal} /></div>{withdrawalsRows.length > 0 && <div className={cardClass}><h2 className={sectionTitleClass}>Lịch sử rút tiền</h2><div className="mt-3 divide-y divide-[#e8eef6]">{withdrawalsRows.slice(0, 5).map((item) => <div key={item.id} className="py-3 text-sm"><div className="flex items-center justify-between gap-2"><b className="text-[#244a7c]">{formatVnd(item.amount)}</b><span className={`rounded-full px-2 py-0.5 text-xs ${withdrawalStatusClass[item.status]}`}>{withdrawalStatusLabel[item.status]}</span></div><p className="mt-1 text-xs text-[#6681a7]">{item.bankName} · {item.bankAccount}</p></div>)}</div></div>}</aside></section>
  </main>;
}
