import "server-only";
import { betterAuth } from "better-auth";
import { drizzleAdapter } from "better-auth/adapters/drizzle";
import { nextCookies } from "better-auth/next-js";
import { db } from "@/db";
import { users, sessions, accounts, verifications } from "@/db/schema";
import { sendEmail, emailLayout } from "@/lib/email";
import { isAdminEmail } from "@/lib/auth/sync";

/**
 * Better Auth server instance.
 *
 * Uses our existing Drizzle schema: `users` is mapped as the Better Auth `user`
 * model (so the rest of the app keeps referencing users.id), plus the auth-owned
 * sessions / accounts / verifications tables. Passwords live in `accounts`.
 * Ids are generated by Postgres (uuid) — generateId is disabled.
 */
export const auth = betterAuth({
  baseURL: process.env.BETTER_AUTH_URL,
  secret: process.env.BETTER_AUTH_SECRET,
  database: drizzleAdapter(db, {
    provider: "pg",
    schema: {
      user: users,
      session: sessions,
      account: accounts,
      verification: verifications,
    },
  }),
  advanced: {
    database: {
      // Let Postgres generate uuids (columns use defaultRandom()).
      generateId: false,
    },
  },
  emailAndPassword: {
    enabled: true,
    requireEmailVerification: true,
    autoSignIn: false,
    minPasswordLength: 6,
    sendResetPassword: async ({ user, url }) => {
      const sent = await sendEmail({
        to: user.email,
        subject: "Đặt lại mật khẩu — Win-Win Back",
        html: emailLayout(
          "Đặt lại mật khẩu",
          `Chào ${user.name || "bạn"}, bạn (hoặc ai đó) đã yêu cầu đặt lại mật khẩu. Nhấn nút bên dưới để tạo mật khẩu mới. Nếu không phải bạn, hãy bỏ qua email này.
           <p style="margin:20px 0"><a href="${url}" style="display:inline-block;background:#b7e961;color:#0d315d;font-weight:700;text-decoration:none;padding:12px 20px;border-radius:10px">Đặt lại mật khẩu</a></p>
           Nếu nút không hoạt động, mở liên kết: <br><a href="${url}">${url}</a>`,
        ),
      });
      if (!sent) {
        console.info(`[reset-password] ${user.email}: ${url}`);
      }
    },
  },
  emailVerification: {
    sendOnSignUp: true,
    autoSignInAfterVerification: true,
    sendVerificationEmail: async ({ user, url }) => {
      const sent = await sendEmail({
        to: user.email,
        subject: "Xác thực email — Win-Win Back",
        html: emailLayout(
          "Xác thực địa chỉ email",
          `Chào ${user.name || "bạn"}, nhấn vào nút bên dưới để xác thực email và kích hoạt tài khoản Win-Win Back.
           <p style="margin:20px 0"><a href="${url}" style="display:inline-block;background:#b7e961;color:#0d315d;font-weight:700;text-decoration:none;padding:12px 20px;border-radius:10px">Xác thực email</a></p>
           Nếu nút không hoạt động, mở liên kết: <br><a href="${url}">${url}</a>`,
        ),
      });
      if (!sent) {
        // Dev fallback when Resend isn't configured — click this from the log.
        console.info(`[verify-email] ${user.email}: ${url}`);
      }
    },
  },
  user: {
    additionalFields: {
      role: {
        type: "string",
        required: false,
        defaultValue: "user",
        input: false,
      },
      balance: {
        type: "number",
        required: false,
        defaultValue: 0,
        input: false,
      },
    },
  },
  databaseHooks: {
    user: {
      create: {
        // Grant admin to configured emails at sign-up time.
        before: async (user) => ({
          data: {
            ...user,
            role: isAdminEmail(user.email) ? "admin" : "user",
          },
        }),
      },
    },
  },
  plugins: [nextCookies()],
});
