export type BankOption = { name: string; code: string; logo: string };

// Logo URLs and bank codes follow VietQR's public bank directory.
export const bankOptions: BankOption[] = [
  { name: "Vietcombank", code: "VCB", logo: "https://cdn.vietqr.io/img/VCB.png" },
  { name: "VietinBank", code: "ICB", logo: "https://cdn.vietqr.io/img/ICB.png" },
  { name: "BIDV", code: "BIDV", logo: "https://cdn.vietqr.io/img/BIDV.png" },
  { name: "Agribank", code: "VBA", logo: "https://cdn.vietqr.io/img/VBA.png" },
  { name: "MB Bank", code: "MB", logo: "https://cdn.vietqr.io/img/MB.png" },
  { name: "Techcombank", code: "TCB", logo: "https://cdn.vietqr.io/img/TCB.png" },
  { name: "ACB", code: "ACB", logo: "https://cdn.vietqr.io/img/ACB.png" },
  { name: "VPBank", code: "VPB", logo: "https://cdn.vietqr.io/img/VPB.png" },
  { name: "TPBank", code: "TPB", logo: "https://cdn.vietqr.io/img/TPB.png" },
  { name: "Sacombank", code: "STB", logo: "https://cdn.vietqr.io/img/STB.png" },
  { name: "HDBank", code: "HDB", logo: "https://cdn.vietqr.io/img/HDB.png" },
  { name: "VIB", code: "VIB", logo: "https://cdn.vietqr.io/img/VIB.png" },
  { name: "SHB", code: "SHB", logo: "https://cdn.vietqr.io/img/SHB.png" },
  { name: "Eximbank", code: "EIB", logo: "https://cdn.vietqr.io/img/EIB.png" },
  { name: "MSB", code: "MSB", logo: "https://cdn.vietqr.io/img/MSB.png" },
  { name: "OCB", code: "OCB", logo: "https://cdn.vietqr.io/img/OCB.png" },
  { name: "SeABank", code: "SEAB", logo: "https://cdn.vietqr.io/img/SEAB.png" },
  { name: "LPBank", code: "LPB", logo: "https://cdn.vietqr.io/img/LPB.png" },
  { name: "ABBank", code: "ABB", logo: "https://cdn.vietqr.io/img/ABB.png" },
  { name: "Bac A Bank", code: "BAB", logo: "https://cdn.vietqr.io/img/BAB.png" },
  { name: "Nam A Bank", code: "NAB", logo: "https://cdn.vietqr.io/img/NAB.png" },
  { name: "VietABank", code: "VAB", logo: "https://cdn.vietqr.io/img/VAB.png" },
  { name: "VietBank", code: "VIETBANK", logo: "https://cdn.vietqr.io/img/VIETBANK.png" },
  { name: "NCB", code: "NCB", logo: "https://cdn.vietqr.io/img/NCB.png" },
  { name: "PVcomBank", code: "PVCB", logo: "https://cdn.vietqr.io/img/PVCB.png" },
  { name: "SCB", code: "SCB", logo: "https://cdn.vietqr.io/img/SCB.png" },
  { name: "BaoVietBank", code: "BVB", logo: "https://cdn.vietqr.io/img/BVB.png" },
  { name: "KienlongBank", code: "KLB", logo: "https://cdn.vietqr.io/img/KLB.png" },
  { name: "Shinhan Bank", code: "SHBVN", logo: "https://cdn.vietqr.io/img/SHBVN.png" },
  { name: "HSBC", code: "HSBC", logo: "https://cdn.vietqr.io/img/HSBC.png" },
  { name: "Woori Bank", code: "WVN", logo: "https://cdn.vietqr.io/img/WVN.png" },
  { name: "CIMB", code: "CIMB", logo: "https://cdn.vietqr.io/img/CIMB.png" },
  { name: "VietCapitalBank", code: "VCCB", logo: "https://cdn.vietqr.io/img/VCCB.png" },
  { name: "Saigonbank", code: "SGICB", logo: "https://cdn.vietqr.io/img/SGICB.png" },
  { name: "PGBank", code: "PGB", logo: "https://cdn.vietqr.io/img/PGB.png" },
  { name: "GPBank", code: "GPB", logo: "https://cdn.vietqr.io/img/GPB.png" },
];
