import { desc, eq } from "drizzle-orm";
import Link from "next/link";
import { BadgeCheck, Check, ChevronDown, ChevronLeft, ChevronRight, CircleDollarSign, Clock3, Copy, Filter, MoreVertical, PackageCheck, RotateCcw, Search, ShoppingBag, Sparkles, WalletCards, XCircle } from "lucide-react";
import Image from "next/image";
import { db } from "@/db";
import { orders } from "@/db/schema";
import { requireUser } from "@/lib/auth/guards";
import { formatVnd } from "@/lib/config";
import { platformLabel } from "@/lib/labels";
import { ShopeeIcon, TikTokIcon } from "@/components/sections/BrandIcons";
import { DateRangeFilter } from "@/components/dashboard/DateRangeFilter";
import { OrderDetailButton } from "@/components/dashboard/OrderDetailButton";
import { Button } from "@/components/ui/button";

export const metadata = { title: "Đơn hàng — Win-Win Back" };
export const dynamic = "force-dynamic";
type Status = "pending" | "confirmed" | "completed" | "cancelled";
const STATUS_META: Record<Status, { label: string; className: string; icon: typeof Clock3 }> = {
  pending: { label: "Đang xử lý", className: "bg-[#fff5df] text-[#e68b00]", icon: Clock3 },
  confirmed: { label: "Đã xác nhận", className: "bg-[#e7f7ef] text-[#168146]", icon: Check },
  completed: { label: "Hoàn tất", className: "bg-[#eaf2ff] text-[#287be5]", icon: BadgeCheck },
  cancelled: { label: "Đã hủy", className: "bg-[#fee9ee] text-[#d34862]", icon: XCircle },
};

function PlatformMark({ platform }: { platform: string }) {
  const isShopee = platform === "shopee";
  return <span className={`flex h-6 w-6 items-center justify-center rounded-md ${isShopee ? "bg-[#ee4d2d]" : "bg-[#101010]"}`}>{isShopee ? <ShopeeIcon className="h-4 w-4" white /> : <TikTokIcon className="h-4 w-4" white />}</span>;
}
function ProductTile({ name }: { name: string }) {
  return <span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-md border border-[#e2eaf4] bg-[#f6f9fd] text-sm font-black text-[#7b9ac1]">{name.trim().charAt(0).toUpperCase() || "S"}</span>;
}
function SummaryCard({ icon: Icon, iconClass, label, value, detail }: { icon: typeof ShoppingBag; iconClass: string; label: string; value: string; detail: React.ReactNode }) {
  return <article className="min-h-[8.25rem] rounded-xl border border-[#e1eaf6] bg-white px-5 py-5 shadow-[0_5px_14px_rgba(26,73,124,0.04)]"><div className="flex items-start gap-4"><span className={`flex h-12 w-12 shrink-0 items-center justify-center rounded-full ${iconClass}`}><Icon className="h-6 w-6" strokeWidth={2.2} /></span><div className="min-w-0"><p className="text-sm font-medium text-[#34527d]">{label}</p><p className="mt-1 text-[26px] font-black leading-none tracking-tight text-[#12335f]">{value}</p><p className="mt-3 text-xs leading-4 text-[#7790b1]">{detail}</p></div></div></article>;
}
export default async function OrdersPage({ searchParams }: { searchParams: Promise<{ status?: string; platform?: string; q?: string; from?: string; to?: string }> }) {
  const user = await requireUser();
  const query = await searchParams;
  const rows = await db.select().from(orders).where(eq(orders.userId, user.id)).orderBy(desc(orders.orderedAt)).limit(100);
  const waiting = rows.filter((row) => row.status === "pending");
  const processing = rows.filter((row) => row.status === "confirmed");
  const complete = rows.filter((row) => row.status === "completed");
  const totalCashback = rows.reduce((sum, row) => sum + row.cashbackAmount, 0);
  const waitingCashback = waiting.reduce((sum, row) => sum + row.cashbackAmount, 0);
  const completeCashback = complete.reduce((sum, row) => sum + row.cashbackAmount, 0);
  const selectedStatus = query.status;
  const keyword = query.q?.trim().toLowerCase() ?? "";
  const startDate = query.from ? new Date(`${query.from}T00:00:00`) : undefined;
  const endDate = query.to ? new Date(`${query.to}T23:59:59.999`) : undefined;
  const validStartDate = startDate && !Number.isNaN(startDate.getTime()) ? startDate : undefined;
  const validEndDate = endDate && !Number.isNaN(endDate.getTime()) ? endDate : undefined;
  const visibleRows = rows.filter((row) => (!selectedStatus || (selectedStatus === "processing" ? row.status === "confirmed" : row.status === selectedStatus)) && (!query.platform || row.platform === query.platform) && (!keyword || [row.productName, row.externalOrderId].some((value) => value.toLowerCase().includes(keyword))) && (!validStartDate || row.orderedAt >= validStartDate) && (!validEndDate || row.orderedAt <= validEndDate));
  const tabs = [{ label: "Tất cả", count: rows.length, href: "/dashboard/don-hang", active: !selectedStatus }, { label: "Chờ xác nhận", count: waiting.length, href: "/dashboard/don-hang?status=pending", active: selectedStatus === "pending" }, { label: "Đang xử lý", count: processing.length, href: "/dashboard/don-hang?status=processing", active: selectedStatus === "processing" }, { label: "Đã xác nhận", count: processing.length, href: "/dashboard/don-hang?status=confirmed", active: selectedStatus === "confirmed" }, { label: "Hoàn tất", count: complete.length, href: "/dashboard/don-hang?status=completed", active: selectedStatus === "completed" }];

  return <main className="mx-auto w-full max-w-[1440px] px-4 py-6 sm:px-7 lg:px-8 lg:py-7">
    <header className="mb-6"><h1 className="text-[28px] font-black leading-tight tracking-tight text-[#11335e] sm:text-[30px]">Đơn hàng của tôi</h1><p className="mt-1 text-sm text-[#58749a]">Theo dõi trạng thái đơn hàng và tiền hoàn của bạn</p></header>
    <nav aria-label="Trạng thái đơn hàng" className="mb-5 flex w-full max-w-[44rem] items-center justify-between gap-2 overflow-x-auto rounded-xl border border-[#dbe7f6] bg-[#f8fbff] p-1">{tabs.map((tab) => <Link key={tab.label} href={tab.href} aria-current={tab.active ? "page" : undefined} className={`inline-flex shrink-0 items-center justify-center gap-2 rounded-lg px-4 py-2.5 text-sm font-medium transition-colors ${tab.active ? "bg-[#edf9df] font-bold text-[#28711a] ring-1 ring-inset ring-[#b1eb78]" : "text-[#34527d] hover:bg-white"}`}>{tab.label}<span className={`rounded-full px-1.5 py-0.5 text-[11px] font-bold ${tab.active ? "bg-[#d8f3bc] text-[#28711a]" : "bg-[#eef3fb] text-[#547299]"}`}>{tab.count}</span></Link>)}</nav>
    <form className="mb-5 grid gap-3 lg:grid-cols-[1.15fr_1.25fr_1.25fr_auto_auto]" action="/dashboard/don-hang">
      <label className="grid gap-1.5 text-xs font-bold text-[#213e67]">Sàn mua sắm<span className="relative"><select name="platform" defaultValue={query.platform ?? ""} className="h-11 w-full appearance-none rounded-lg border border-[#d9e5f4] bg-white px-3 pr-10 text-sm font-medium text-[#35537c] outline-none transition focus:border-[#8bd950] focus:ring-2 focus:ring-[#b7e961]/25"><option value="">Tất cả sàn</option><option value="shopee">Shopee</option><option value="tiktok">TikTok Shop</option></select><ChevronDown className="pointer-events-none absolute right-3 top-1/2 h-4 w-4 -translate-y-1/2 text-[#547299]" /></span></label>
      <label className="grid gap-1.5 text-xs font-bold text-[#213e67]">Mã đơn hàng<span className="relative"><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-[#5779a7]" /><input name="q" defaultValue={query.q} placeholder="Nhập mã đơn hàng, sản phẩm..." className="h-11 w-full rounded-lg border border-[#d9e5f4] bg-white px-10 text-sm text-[#35537c] outline-none placeholder:text-[#8ba0bd] focus:border-[#8bd950] focus:ring-2 focus:ring-[#b7e961]/25" /></span></label>
      <DateRangeFilter defaultFrom={query.from} defaultTo={query.to} />
      <div className="flex items-end"><Link href="/dashboard/don-hang" className="inline-flex h-11 items-center justify-center gap-2 rounded-lg border border-[#d9e5f4] bg-white px-4 text-sm font-bold text-[#34527d] transition hover:bg-[#f6f9fd]"><RotateCcw className="h-4 w-4" /> Xóa bộ lọc</Link></div>
      <div className="flex items-end"><Button type="submit" variant="cta" className="h-11 gap-2 rounded-lg px-5 text-sm font-bold"><Filter className="h-4 w-4" /> Lọc kết quả</Button></div>
    </form>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><SummaryCard icon={ShoppingBag} iconClass="bg-[#e7f1ff] text-[#287be5]" label="Tổng đơn hàng" value={String(rows.length)} detail="Trong khoảng thời gian đã chọn" /><SummaryCard icon={Clock3} iconClass="bg-[#fff1d9] text-[#e99a10]" label="Đang chờ hoàn tiền" value={String(waiting.length)} detail={<>Tổng tiền: <b className="text-[#f06b2e]">{formatVnd(waitingCashback)}</b></>} /><SummaryCard icon={PackageCheck} iconClass="bg-[#e8f9df] text-[#3ba818]" label="Đã hoàn tất" value={String(complete.length)} detail={<>Tổng tiền: <b className="text-[#168146]">{formatVnd(completeCashback)}</b></>} /><SummaryCard icon={WalletCards} iconClass="bg-[#f6e9ff] text-[#aa34de]" label="Tổng tiền hoàn" value={formatVnd(totalCashback)} detail="Tất cả đơn hàng" /></div>
    <section className="mt-5 grid gap-4 xl:grid-cols-[minmax(0,1fr)_18rem]">
      <div className="overflow-hidden rounded-xl border border-[#dfe9f5] bg-white shadow-[0_5px_14px_rgba(26,73,124,0.04)]"><div className="overflow-x-auto"><table className="min-w-[950px] w-full text-left"><thead className="border-b border-[#dfe9f5] bg-[#f8fbff] text-xs font-bold text-[#234168]"><tr><th className="px-5 py-4">Sàn</th><th className="px-3 py-4">Mã đơn hàng</th><th className="px-3 py-4">Sản phẩm</th><th className="px-3 py-4">Giá trị đơn</th><th className="px-3 py-4">Tiền hoàn</th><th className="px-3 py-4">Trạng thái</th><th className="px-3 py-4">Ngày mua</th><th className="px-4 py-4 text-center">Hành động</th></tr></thead><tbody className="divide-y divide-[#e8eef6]">
        {visibleRows.length === 0 ? <tr><td colSpan={8} className="px-5 py-16 text-center text-sm text-[#6681a7]">Không có đơn hàng phù hợp với bộ lọc này.</td></tr> : visibleRows.map((row) => { const status = STATUS_META[row.status as Status]; const StatusIcon = status.icon; return <tr key={row.id} className="text-xs text-[#35537c] transition-colors hover:bg-[#fbfdff]"><td className="px-5 py-3.5"><div className="flex items-center gap-2"><PlatformMark platform={row.platform} /><span className="font-medium">{platformLabel[row.platform]}</span></div></td><td className="px-3 py-3.5"><div className="flex items-center gap-1.5 font-medium"><span>{row.externalOrderId}</span><Copy className="h-3.5 w-3.5 text-[#90a5c2]" /></div></td><td className="px-3 py-3.5"><div className="flex max-w-[15rem] items-center gap-2.5"><ProductTile name={row.productName} /><span className="line-clamp-2 font-semibold leading-4 text-[#244a7c]">{row.productName}</span></div></td><td className="px-3 py-3.5 font-medium">{formatVnd(row.orderAmount)}</td><td className="px-3 py-3.5 font-bold text-[#168146]">{formatVnd(row.cashbackAmount)}</td><td className="px-3 py-3.5"><span className={`inline-flex items-center gap-1 rounded-full px-2.5 py-1 text-[11px] font-bold ${status.className}`}><StatusIcon className="h-3.5 w-3.5" />{status.label}</span></td><td className="px-3 py-3.5 leading-4">{row.orderedAt.toLocaleDateString("vi-VN")}<br /><span className="text-[#7790b1]">{row.orderedAt.toLocaleTimeString("vi-VN", { hour: "2-digit", minute: "2-digit" })}</span></td><td className="px-4 py-3.5"><div className="flex items-center justify-center gap-2"><OrderDetailButton order={{ platformLabel: platformLabel[row.platform], externalOrderId: row.externalOrderId, productName: row.productName, orderAmount: formatVnd(row.orderAmount), commissionAmount: formatVnd(row.commissionAmount), cashbackAmount: formatVnd(row.cashbackAmount), statusLabel: status.label, statusClass: status.className, orderedAt: row.orderedAt.toLocaleString("vi-VN") }} /><button aria-label={`Thêm lựa chọn cho đơn ${row.externalOrderId}`} className="rounded p-1 text-[#36557f] hover:bg-[#eef4fc]"><MoreVertical className="h-4 w-4" /></button></div></td></tr>; })}
      </tbody></table></div><footer className="flex flex-col gap-3 border-t border-[#e8eef6] px-5 py-4 text-xs text-[#6d87aa] sm:flex-row sm:items-center sm:justify-between"><p>Hiển thị 1 - {visibleRows.length} trong tổng số {visibleRows.length} đơn hàng</p><div className="flex items-center gap-2"><button aria-label="Trang trước" className="rounded-lg border border-[#dce6f3] p-1.5"><ChevronLeft className="h-4 w-4" /></button><span className="flex h-7 w-7 items-center justify-center rounded-md bg-[#eaf9df] font-bold text-[#28711a] ring-1 ring-inset ring-[#b1eb78]">1</span><button aria-label="Trang sau" className="rounded-lg border border-[#dce6f3] p-1.5"><ChevronRight className="h-4 w-4" /></button></div></footer></div>
      <aside className="space-y-4"><section className="rounded-xl border border-[#e1eaf6] bg-white p-5 shadow-[0_5px_14px_rgba(26,73,124,0.04)]"><h2 className="flex items-center gap-2 text-sm font-bold text-[#173861]"><Sparkles className="h-4 w-4 text-[#f5b613]" /> Mẹo để đơn được ghi nhận hoàn tiền</h2><ul className="mt-5 space-y-5"><li className="flex gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-[#edf9e7] text-[#32a51f]"><ShoppingBag className="h-5 w-5" /></span><div><b className="text-xs text-[#244a7c]">Mua sắm qua Win-Win Back</b><p className="mt-1 text-xs leading-4 text-[#6e88ab]">Luôn truy cập sàn thương mại qua Win-Win Back để đơn được ghi nhận.</p></div></li><li className="flex gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-[#edf9e7] text-[#32a51f]"><CircleDollarSign className="h-5 w-5" /></span><div><b className="text-xs text-[#244a7c]">Không sử dụng mã ngoài</b><p className="mt-1 text-xs leading-4 text-[#6e88ab]">Không dùng mã giảm giá ngoài sàn để đảm bảo nhận hoàn tiền.</p></div></li><li className="flex gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-[#edf9e7] text-[#32a51f]"><Clock3 className="h-5 w-5" /></span><div><b className="text-xs text-[#244a7c]">Chờ đủ thời gian hoàn</b><p className="mt-1 text-xs leading-4 text-[#6e88ab]">Tiền hoàn sẽ được xác nhận sau khi hết thời gian đổi trả.</p></div></li></ul></section><section className="relative min-h-[13.5rem] overflow-hidden rounded-xl border border-[#dcefcf] bg-[#effde8] p-5"><div className="absolute inset-y-0 right-0 z-0 w-1/2"><Image src="/images/dashboard-cashback-tracking-promo-v1.png" alt="Linh vật Win-Win Back theo dõi tiền hoàn" fill sizes="9rem" className="object-cover object-right" priority /></div><div aria-hidden="true" className="pointer-events-none absolute inset-y-0 left-0 z-10 w-1/2 bg-[#effde8]" /><div className="relative z-20 max-w-36"><h2 className="text-sm font-bold leading-5 text-[#173861]">Theo dõi hoàn tiền dễ dàng</h2><p className="mt-2 text-xs leading-4 text-[#49688f]">Win-Win Back sẽ tự động cập nhật trạng thái đơn hàng và tiền hoàn của bạn.</p><Link href="/dashboard" className="mt-4 inline-flex w-full items-center justify-between rounded-lg bg-[#a9e75e] px-3 py-2 text-xs font-bold text-[#173b5e] shadow-[0_3px_6px_rgba(99,180,45,0.18)] transition hover:bg-[#b7e961]">Tìm hiểu thêm <ChevronRight className="h-3.5 w-3.5" /></Link></div></section></aside>
    </section>
  </main>;
}
