import Link from "next/link";
import { CalendarDays, ChevronRight, Mail, ShieldCheck, User } from "lucide-react";
import Image from "next/image";
import { requireUser } from "@/lib/auth/guards";
import { PageHeader, cardClass, sectionTitleClass } from "@/components/dashboard/ui";
import { ProfileForm } from "@/components/dashboard/ProfileForm";

export const metadata = { title: "Tài khoản — Win-Win Back" };
export const dynamic = "force-dynamic";

function Setting({ icon: Icon, title, description }: { icon: typeof User; title: string; description: string }) { return <div className="flex items-center gap-3 border-b border-[#e8eef6] py-4 last:border-0"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#eef4fc] text-[#3172c8]"><Icon className="h-[18px] w-[18px]" /></span><div className="min-w-0 flex-1"><p className="font-semibold text-[#244a7c]">{title}</p><p className="mt-0.5 text-xs text-[#6681a7]">{description}</p></div></div>; }

export default async function AccountPage() {
  const user = await requireUser();
  return <main className="mx-auto max-w-[1440px] px-4 py-7 sm:px-7 lg:px-6 lg:py-8"><PageHeader icon={User} title="Cài đặt" hint="Quản lý thông tin tài khoản và tùy chọn sử dụng của bạn." />
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><div className={cardClass}><p className="text-xs text-[#6681a7]">Hồ sơ tài khoản</p><p className="mt-2 font-bold text-[#238a24]">Đã xác minh</p></div><div className={cardClass}><p className="text-xs text-[#6681a7]">Bảo mật</p><p className="mt-2 font-bold text-[#238a24]">An toàn</p></div><div className={cardClass}><p className="text-xs text-[#6681a7]">Thông báo</p><p className="mt-2 font-bold text-[#238a24]">Đang bật</p></div><div className={cardClass}><p className="text-xs text-[#6681a7]">Vai trò</p><p className="mt-2 font-bold text-[#244a7c]">{user.role === "admin" ? "Quản trị viên" : "Người dùng"}</p></div></div>
    <section className="mt-5 grid gap-5 xl:grid-cols-[minmax(0,1fr)_20rem]"><div className="space-y-5"><div className={cardClass}><h2 className={sectionTitleClass}>Thông tin cá nhân</h2><div className="mt-5 flex items-center gap-4"><span className="flex h-16 w-16 items-center justify-center rounded-full bg-[#b7e961] text-2xl font-black text-[#0a3b60]">{user.name.trim().charAt(0).toUpperCase()}</span><div><p className="text-lg font-bold text-[#0d315d]">{user.name}</p><p className="mt-1 text-sm text-[#6681a7]">{user.email}</p></div></div><ProfileForm name={user.name} email={user.email} /><div className="mt-5 divide-y divide-[#e8eef6]"><Setting icon={Mail} title="Email" description={user.email} /><Setting icon={CalendarDays} title="Tham gia từ" description={user.createdAt.toLocaleDateString("vi-VN", { day: "2-digit", month: "2-digit", year: "numeric" })} /></div></div><div className={cardClass}><h2 className={sectionTitleClass}>Bảo mật tài khoản</h2><div className="mt-2"><Setting icon={ShieldCheck} title="Thông tin đăng nhập" description="Chức năng đổi mật khẩu sẽ được bổ sung trong bản cập nhật sau." /></div></div></div><aside className="space-y-4"><div className="relative min-h-56 overflow-hidden rounded-xl bg-[#effbdd] p-5"><Image src="/images/dashboard-security-promo-v2.png" alt="" fill sizes="20rem" className="object-contain object-right sm:object-cover sm:object-center" /><div className="relative z-10 max-w-[10rem] sm:max-w-[11rem]"><h2 className="text-lg font-black text-[#164b37]">Tài khoản luôn được bảo vệ</h2><p className="mt-3 text-sm leading-5 text-[#356b54]">Không chia sẻ thông tin đăng nhập với người khác.</p></div></div><div className={cardClass}><h2 className={sectionTitleClass}>Thông tin hữu ích</h2><ul className="mt-4 space-y-3 text-sm leading-5 text-[#6681a7]"><li>✓ Theo dõi đơn hàng để nhận tiền hoàn đúng hạn.</li><li>✓ Liên hệ hỗ trợ khi cần trợ giúp.</li></ul></div>{user.role === "admin" && <Link href="/admin" className="flex items-center justify-between rounded-xl bg-[#effbdd] p-5 font-bold text-[#315c24]">Trang quản trị <ChevronRight className="h-5 w-5" /></Link>}</aside></section>
  </main>;
}
